### ISSUE TITLE
How to find the lat/ lon values for LLC

### ISSUE THREAD

**Issue by dhruvbalwada** [MITgcm/xmitgcm#161]
Maybe this is still in the works, but is there some way to figure out the lat-lon values for the data? 

When I read in the data following the binder example (https://binder.pangeo.io/v2/gh/pangeo-data/pangeo-ecco-llc/master?filepath=visualize_SST.ipynb) there is no lat/lon information, just indices i,j. 

Maybe an example on how to do this would be useful. 

#158 #154 might be related.

**Comment by timothyas** [comment]
Hey @dhruvbalwada, I have not played with the llcreader module much, other than quickly running that binder example you linked to, but lat/lon values are typically shown as YC/XC data arrays. Because of the weird LLC grid, these are essentially 2D fields which are accessed along the i,j dimensions just like a data variable. 

When one reads in LLC output from an MITgcm run with xmitgcm, [like here for LLC90](https://xmitgcm.readthedocs.io/en/latest/demo_read_input_grid.html#Example-1:-LLC90), it reads in grid information to dataset coordines. You can see the XC/YC arrays which have the (face, j, i) dimensions just like any other 2D field. These are the appropriate lon/lat pairs for cell centered values like theta. For zonal velocity quantities it would be XG/YC, meridional XC/YG, [corresponding to their location on a C grid](https://mitgcm.readthedocs.io/en/latest/algorithm/horiz-grid.html).

Taking a quick look at the [ECCO portal](https://mitgcm.readthedocs.io/en/latest/algorithm/horiz-grid.html) I don't see any grid information for llcreader to grab. Maybe there is a more simple solution (forgive me since I haven't used llcreader much), but maybe someone from ECCO could make the grid information available on the portal? I'll tag a couple of folks who may be able to help you out with that grid info: @owang01 @ifenty @menemenlis

**Comment by mpielies** [comment]
Hi @dhruvbalwada and @timothyas  !

I'm facing the same problem but using the LLC4320 model. The xmitgcm.llcreader get_dataset() function doesn't have an input parameter like the xmitgcm.open_mdsdataset(...,swap_dims = False/True,...) and I don't know where or how I can find them (if they exist in that model).

I would be very interested on obtaining these coordinates so any help is welcome!

**Comment by antonimmo** [comment]
What I did is the following:

1. Load the LLC2160 grid (I downloaded its files):

`from xmitgcm import open_mdsdataset`
`grid_ds = open_mdsdataset('/my/grid/folder/', read_grid=True, iters=None, default_dtype=np.float32, geometry='llc')`

2. Interpolate XG,YG,XC,YC to (4320,4320) matrices

3. Map (lon,lat) to (j,i) or viceversa.

**Comment by antonimmo** [comment]
Update: Most of the LLC4230 grid is already available
https://data.nas.nasa.gov/ecco/data.php?dir=/eccodata/llc_4320/grid, but I had to "infer" some meta files by myself, based on the ones from LLC2160.

> What I did is the following:
> 
> 1. Load the LLC2160 grid (I downloaded its files):
> 
> `from xmitgcm import open_mdsdataset`
> `grid_ds = open_mdsdataset('/my/grid/folder/', read_grid=True, iters=None, default_dtype=np.float32, geometry='llc')`
> 
> 1. Interpolate XG,YG,XC,YC to (4320,4320) matrices
> 2. Map (lon,lat) to (j,i) or viceversa.

**Comment by menemenlis** [comment]
Hi Antonio, the meta files should be available now.  Apologies for accidental deletion.  Dimitris
