### ISSUE TITLE
ecco portal weird looking wind stress

### ISSUE THREAD

**Issue by apatlpo** [MITgcm/xmitgcm#191]
I am loading wind stress data from the ecco portal but the data looks weird:

![image](https://user-images.githubusercontent.com/11750960/75198883-84f88d00-5716-11ea-92a8-9b9713d430b4.png)

Has anybody seen this before?

See the following [gist](https://gist.github.com/apatlpo/1f2bd9c106c3de980b012666c84c69bb) for more details about how I got the figure above.

ping @rabernat

**Comment by rabernat** [comment]
So my first impression about this is that it is a mask issue. The way the data are compressed is by removing all of the land points, as defined in hFacC / hFacW / hFacS. To uncompress, we need to fill in all of these missing points. The nature of how this image looks distorted makes me think that there is a mismatch between the mask we are assuming and the true mask used to compress the data.

Right now, the mask is determined based on the grid location:
https://github.com/MITgcm/xmitgcm/blob/876786c413488f6be0cb0b479064a9cd2f68b6b5/xmitgcm/llcreader/llcmodel.py#L35-L47

Since `oceTAUX` is at the U velocity point (`i_g, j`), it uses the same mask as U (`hFacW`). You can confirm that U does indeed look right--this is how I debugged the routines initially. But for some reason, this is not working for oceTAUX, oceTAUY.

It would be good if we could verify with the creators of this dataset (i.e. Dimitris), whether a different mask was used in compressing the wind stress.

**Comment by apatlpo** [comment]
thanks Ryan, this makes very much sense.
While waiting for an answer from Dimitris, I'll tweak xmitgcm to use other masks and see if it helps.

**Comment by rabernat** [comment]
One clue is that taux and tauy seem to have the exact same file size as the c-grid variables:
```
-r--r--r-- 1 dmenemen g26209  140637812 Mar  4  2017 oceSflux.0000092240.data.shrunk
-r--r--r-- 1 dmenemen g26209  140637812 Mar  4  2017 oceTAUX.0000092240.data.shrunk
-r--r--r-- 1 dmenemen g26209  140637812 Mar  4  2017 oceTAUY.0000092240.data.shrunk
```

That suggests they should have the same mask. So try to force it to use the `hFacC` mask.

**Comment by rabernat** [comment]
Yes, that is it. This works
```diff
diff --git a/xmitgcm/llcreader/llcmodel.py b/xmitgcm/llcreader/llcmodel.py
index 8b5e069..90a3aee 100644
--- a/xmitgcm/llcreader/llcmodel.py
+++ b/xmitgcm/llcreader/llcmodel.py
@@ -33,6 +33,7 @@ def _get_var_metadata():
 _VAR_METADATA = _get_var_metadata()
 
 def _get_variable_point(vname):
+    return 'c'
     dims = _VAR_METADATA[vname]['dims']
     if 'i' in dims and 'j' in dims:
         point = 'c'
```

![image](https://user-images.githubusercontent.com/1197350/75278390-c8ff9680-57d7-11ea-8779-c524a1a39b40.png)

So now the question is: **is oceTAUX actually located at the cell center?** This is definitely not what `available-diagnostics.log` says:
https://github.com/MITgcm/xmitgcm/blob/14c73384d5a77caede95fb2185a8d9a4c1bdd5c0/xmitgcm/default_diagnostics.py#L87-L88

There are three possibilities:
1. `available-diagnostics.log` is wrong
1. `oceTAUX` and `oceTAUY` were interpolated to cell centers in the LLC runs.
1. `oceTAUX` and `oceTAUY` were compressed with the c-grid mask, despite being located at velocity points.

Which one of these is the case determines what is the best course of actions.

Pinging @menemenlis, although it's unlikely he is paying attention to this thread.

**Comment by apatlpo** [comment]
thanks Ryan, I was able to override the default behavior in a rather flexible way, see 98c6472
 and updated the [gist](https://gist.github.com/apatlpo/b4c651b18d99230c1587fbdb9dc78116)

Let's wait to see @menemenlis answer.

For our applications, the uncertainty around the precise location of taux and tauy is not critical and we will be able to proceed, many thanks

**Comment by menemenlis** [comment]
Hi all, apologies for delayed response and for lack of proper llc4320 documentation.

I confirm that "oceTAUX and oceTAUY were compressed with the c-grid mask, despite being located at velocity points”.

The llc4320 model output was done with non-standard diagnostics
http://wwwcvs.mitgcm.org/viewvc/MITgcm/MITgcm_contrib/llc_hires/llc_4320/code-async/
so available-diagnostics.log does not (necessarily) apply.

The relevant routines in this case are:
http://wwwcvs.mitgcm.org/viewvc/MITgcm/MITgcm_contrib/llc_hires/llc_4320/code-async/recvTask.c
http://wwwcvs.mitgcm.org/viewvc/MITgcm/MITgcm_contrib/llc_hires/llc_4320/code-async/write_state.F
and I have verified that:

  { 'I', MPI_COMM_NULL, MPI_COMM_NULL, MPI_COMM_NULL, 0, -1, "oceTAUX.%010d.%s", 0,0 },
  { 'J', MPI_COMM_NULL, MPI_COMM_NULL, MPI_COMM_NULL, 0, -1, "oceTAUY.%010d.%s", 0,0 },

        CALL ASYNCIO_WRITE_FLD_XY_RL('I',suff,fu,iCounter,myThid)
        CALL ASYNCIO_WRITE_FLD_XY_RL('J',suff,fv,iCounter,myThid)

meaning that oceTAUX and oceTAUY are simply fu and fv:

C     fu    :: Zonal surface wind stress in N/m^2
C              > 0 for increase in uVel, which is west to
C                  east for cartesian and spherical polar grids
C              Southwest C-grid U point
C
C     fv    :: Meridional surface wind stress in N/m^2
C              > 0 for increase in vVel, which is south to
C                  north for cartesian and spherical polar grids
C              Southwest C-grid V point

That is, they have not been interpolated to cell centers.

From the size of SIuice, SIvice, oceTAUX, and oceTAUY:

-r--r--r-- 1 dmenemen g26209   562551864 May 20  2017 Eta.0001495008.data.shrunk
-r--r--r-- 1 dmenemen g26209   562551864 May 20  2017 SIuice.0001495008.data.shrunk
-r--r--r-- 1 dmenemen g26209   562551864 May 20  2017 SIvice.0001495008.data.shrunk
-r--r--r-- 1 dmenemen g26209   562551864 May 20  2017 oceTAUX.0001495008.data.shrunk
-r--r--r-- 1 dmenemen g26209   562551864 May 20  2017 oceTAUY.0001495008.data.shrunk

You can see that same mask was applied to all 2D variables.
This is OK since the tracer masks are less restrictive than the velocity masks.
Only for U/V were the c-grid edge masks applied.

Dimitris

**Comment by apatlpo** [comment]
Thanks a lot Dimitris for the explanation.

98c6472 proposes a mitigation measure for this case but I feel it's a bit invasive.

**Comment by rabernat** [comment]
I just implemented a fix for this in #192.

I'm really not sure what https://github.com/MITgcm/xmitgcm/commit/98c64724a7c906b3020edba22721481eb6e84343 even is! Where is this commit? How was it added to the repo without a PR? What branch does it live on?

The best way to propose a change to the project is to fork it and make a PR from a feature branch in your fork.

**Comment by apatlpo** [comment]
thanks for this

**Comment by rabernat** [comment]
> [98c6472](https://github.com/MITgcm/xmitgcm/commit/98c64724a7c906b3020edba22721481eb6e84343) was a commit on a forked repo

But was it? That commit lives in the main MITgcm/xmitgcm repo. I'm just confused! Probably means it's time to 😴. 

> Thanks in any case for your efforts around xmitgcm, the library is proving itself to be very useful to our group!

Great to hear! I'm so excited by these simulations. I can't wait to learn more about the science you're working on. (In fact, wish science itself could be more collaborative, like working on code on github 😉!)
