### ISSUE TITLE
faces_dataset_to_latlon produces singleton j_g dask chunks

### ISSUE THREAD

**Issue by apatlpo** [MITgcm/xmitgcm#215]
`faces_dataset_to_latlon singleton`  produces dataset that have singleton `j_g` chunks:
```
ds_rt = llc.faces_dataset_to_latlon(ds)
ds_rt['SSV'].chunks
```
outputs:
```
((1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
 (1, 4319, 1, 4319, 1, 4319),
 (4320, 4320, 4320, 4320))
```

Is this intended?

If not, I can propose a rechunking scheme to get rid of this behavior.

**Comment by rabernat** [comment]
This chunk structure is a consequence of the padding that is necessary to apply to the U-grid variables in order to make them the same size as the V-grid variables after rotation:

https://github.com/MITgcm/xmitgcm/blob/f5ee774f6ee3788d48f32a9bd1fbe02ebea9449b/xmitgcm/llcreader/llcmodel.py#L210-L219

I'm not sure there is any way around this. But you are free to call `.rechunk(j_g=something_else)` on the output.

Can you explain why this is a problem for your analysis?

**Comment by apatlpo** [comment]
It is not a problem to the analysis yet and I don't think it will be.
I got however confused for a moment by the array and dask representations of the arrays.
For example `ds_rt['SSV']` produces:

![image](https://user-images.githubusercontent.com/11750960/88559656-61bb6c00-d02d-11ea-9cbd-fb722a6c04c6.png)

while `ds_rt['SSV'].data` produces:

![image](https://user-images.githubusercontent.com/11750960/88559733-7f88d100-d02d-11ea-8019-2985467c3374.png)

The xarray representation raised my concern initially.
This is a minor point really.

**Comment by apatlpo** [comment]
I am going to close this non-issue for now, it seems to be a xarray/dask one at best.
