### ISSUE TITLE
Lazy `open_mdsdataset`

### ISSUE THREAD

**Issue by aulemahal** [MITgcm/xmitgcm#229]
With xmitgcm 0.4.1 and xarray 0.16.2, it appears that `open_mdsdataset` is not _lazy_, it loads data somewhere in the process, which can use huge amounts of memory with large datasets.
The culprit is `xr.combine_by_coords` here: 
https://github.com/MITgcm/xmitgcm/blob/a5d297978ab43326e933548e18735d2db9aabd3a/xmitgcm/mds_store.py#L241
If I understand correctly, xarray receives variables without indexes and must resolve to loading some data to make the merge. Changing the line to: 
```python3
ds = xr.combine_by_coords(datasets, compat='override', coords='minimal', combine_attrs='drop')
```
I had seemingly the same output, but with no data loading, memory use stayed low, and opening the file was much faster. 

However, I'm guessing this might not be a general fix? My `open_mdsdataset` looks like:
```python3
ds = open_mdsdataset('output/folder/', prefix='dynDiag', delta_t=1, geometry='cartesian', ignore_unknown_vars=True)
```
Data was generated using the `diagnostics` package.

I would have time for a PR, but I don't know xmitgcm enough to see all possible edge cases here!

**Comment by rabernat** [comment]
Thanks @aulemahal. It definitely **should** be lazy and indeed is lazy in most circumstances. However, there may have been some upstream changes in xarray that affected this. Your issue is also closely related to #227 

We would gladly accept a RP with your proposed changes. Our test suite should hopefully catch any possible issues.
