### ISSUE TITLE
Further fixes to k_u, k_l, Z_u, and Z_l

### ISSUE THREAD

**Issue by ifenty** [MITgcm/xmitgcm#251]
@rabernat 

I suspect that we also need to update 'c_grid_axis_shift' in **k_u** and **k_l,** not just their names.  If I  understand the comodo convention correctly, **k_u** should have **c_grid_axis_shift=-0.5** because the 'upper_w_location' comes 'before' (above) the center of the tracer grid points.  Similarly, **k_l** should have **c_grid_axis_shift=0.5** because it is shifted by half an index 'after' (below) the center of tracer grid points. Is that right?

Also, I'm feeling a little nervous about the downstream effects of fixing the descriptions of **k_u** and **k_l**. Until yesterday's pull request, xmitgcm assigned **k_l** as the dimension coordinate for vertical velocity (WVEL, WVELMASS) and vertical flux variables (e.g., ADVr_TH, ADVr_SALT). In other words, variables like ADVr_SALT were assigned dimensions ADVr_SALT(i, j, **k_l**, t). Until yesterday, **k_l** was described as the 'upper_w_location' of grid cells and **Z_l** was described as the depth at the 'upper_w_location'. Thus, putting aside the confusing swap of 'l' and 'u' in the coordinate names, at least the _use_ of  **k_l** and **Z_l** was correct since in MITgcm vertical velocity and vertical flux variables count 'down' starting from the top of the surface grid cell. 

My nervousness comes because I see that by fixing the names of **k_u**, **k_l**, **Z_u**, and **Z_l**, xmitgcm will (should) now use **k_u** as the vertical dimension for our vertical velocity and vertical flux variables. In other words, where we formerly had ADVr_TH(i ,j, **k_l**, t) we will now have ADVr_TH(i ,j, **k_u**, t).

Taking the long view, I think we shouldn't hesitate to fix these kinds of bugs because by doing so we are helping to make analysis easier for everyone.  In the short term, however, I know that a bunch of files will be floating around with inconsistent dimension names. It's probably really not a big deal, and god knows we've come a long way in improving the structure and description of these fields, but I think it's worth pointing out.

**Comment by AaronDavidSchneider** [comment]
I think it would be really helpful to have a scetch somewhere in the documentation (maybe like this one: https://xgcm.readthedocs.io/en/latest/_images/grid2d_hv.svg but with an explanation of the indices instead of vector components).

**Comment by ifenty** [comment]
Aaron, something like this figure [C-grid indices](https://ecco-v4-python-tutorial.readthedocs.io/_images/C-grid-points.png) from https://ecco-v4-python-tutorial.readthedocs.io/ECCO_v4_Coordinates_and_Dimensions_of_ECCOv4_NetCDF_files.html ?

**Comment by ifenty** [comment]
I am afraid I might have opened a can of worms here.  For xmitgcm to use **k_u**  for the vertical dimension for variables like ADVr_TH, the 'parse_available_diagnostics' routine will need to be updated, in addition to a few other places where **k_l** is hard coded as the vertical dimension for state and other variables.

I wrote @jm-c an email asking to clarify the diagnostics codes for these 3D vertical velocity/flux fields. Hopefully we'll hear from him soon.

**Comment by AaronDavidSchneider** [comment]
> Aaron, something like this figure [C-grid indices](https://ecco-v4-python-tutorial.readthedocs.io/_images/C-grid-points.png) from https://ecco-v4-python-tutorial.readthedocs.io/ECCO_v4_Coordinates_and_Dimensions_of_ECCOv4_NetCDF_files.html ?

Thanks! Yes indeed that is a very nice overview.

**Comment by rabernat** [comment]
A big part of the confusion here is the difference between logical grid space and physical grid space. The uppermost vertical cell face (the top of the ocean) is the _lowest_ logical position (index 0). `c_grid_axis_shift` refers to the logical grid, not the physical grid.

The original choices I made (before #250) were as follows (see [docs](https://xmitgcm.readthedocs.io/en/latest/usage.html#dimensions-and-coordinates))

name | standard_name
-- | --
time | time
XC | longitude
YC | latitude
XG | longitude_at_f_location
YG | latitude_at_f_location
Zl | depth_at_upper_w_location
Zu | depth_at_lower_w_location
Z | depth
Zp1 | depth_at_w_location



name | standard_name | axis | c_grid_axis_shift
-- | -- | -- | --
i | x_grid_index | X |  
i_g | x_grid_index_at_u_location | X | -0.5
j | y_grid_index | Y |  
j_g | y_grid_index_at_v_location | Y | -0.5
k | z_grid_index | Z |  
k_u | z_grid_index_at_lower_w_location | Z | -0.5
k_l | z_grid_index_at_upper_w_location | Z | 0.5
k_p1 | z_grid_index_at_w_location | Z | (-0.5, 0.5)

Vertical velocity `W` has dimensions `('time', 'Zl', 'YC', 'XG')`. 

The `l` in `Zl` refers to the lower _logical_ grid position. But the description, `depth_at_upper_w_location`, refers to the physical location. MITgcm's mnc package gives the MNC coordinate `Rl` the description 'R coordinate of lower interface'.

https://github.com/MITgcm/MITgcm/blob/53920f7e3300bb2625dda77e1cd56e7284b7b03e/model/src/ini_mnc_vars.F#L110-L114

This appears to refer to to the logical position. In an atmospheric simulation, the lower _logical_  lower interface is also the lower _physical_ interface.

MITgcm does use `Rl` as the coordinate for `W`:

https://github.com/MITgcm/MITgcm/blob/53920f7e3300bb2625dda77e1cd56e7284b7b03e/model/src/ini_mnc_vars.F#L278

This is consistent with how we label things.

So from my point of view, it seems that #250 did make our naming consistent with MITgcm; xmitgcm now _only_ refers to logical grid position.

The one remaining inconsistency is `c_grid_axis_shift`. Since `Kl` / `Zl` is the "left" position (lower logical position), it should be -0.5.

**Comment by rabernat** [comment]
Looking at the code, it seems like we are actually already doing the right thing with `k_l`

https://github.com/MITgcm/xmitgcm/blob/ea0a18e1ef2470669e381ae9c51e2c0b052071e9/xmitgcm/variables.py#L56-L59

This is inconsistent with the documentation however.

So really I think we just need documentation fixes.

**Comment by ifenty** [comment]
@rabernat  said:
> So from my point of view, it seems that #250 did make our naming consistent with MITgcm; xmitgcm now _only_ refers to logical grid position.

OK... To recap, for ocean variables:

**k_l** will index variables whose first value is physically at the top of the uppermost grid cell (the sea surface),  with c_grid_axis_shift=-0.5, meaning it is logically before (but physically above) the center of the first tracer cell. 
**Z_l** are the depths associated with **k_l**, starting from 0m.

**k_u** will index variables whose first value is physically at the bottom of the uppermost grid cell, with c_grid_axis_shift=+0.5, meaning it is logically after (physically below) the first tracer cell. 
**Z_u** are the depths associated with **k_u**, starting from -10m (at least for ECCO V4)

The words 'lower' and 'upper' in the descriptions of **k_l**,  **k_u**, **Z_l**, and **Z_u** will now _only_ refer to the _logical grid_, whose lowest value is physically at the sea surface and whose uppermost value is physically at the bottom of the deepest grid cell.

With enough clear documentation we should be able to minimize the confusion, even though to a newcomer (and even not so newcomers) the labelling is unintuitive! :)

**Comment by rabernat** [comment]
I just made a PR to the docs (#252) which tries to explain all of this. @ifenty your review there would be much appreciated.
