### ISSUE TITLE
llcreader with ECCO HTTP Data Portal

### ISSUE THREAD

**Issue by koldunovn** [MITgcm/xmitgcm#266]
In the documentation (https://xmitgcm.readthedocs.io/en/latest/llcreader.html#ecco-http-data-portal) there is a link to "ECCO HTTP Data Portal" (https://data.nas.nasa.gov/ecco/) that seems to be down for several days already. Do you know if it's a temporary technical problem, or service is not available anymore?

**Comment by nicolasdettling** [comment]
As I understand, the site was down due to maintenance. Apparently, the maintenance period has been extended until May 22nd. The site is now back online but reads: "Data Portal file download service will be unavailable Wednesday, May 12th 7 a.m. PDT through Saturday, May 22nd for system maintenance. We apologize for any inconvenience."

**Comment by koldunovn** [comment]
Thanks for clarification, @nicolasdettling ! For me it was just down for several days. Looks like it just some temporary problems.
