### ISSUE TITLE
LLCreader2160 Sea Ice Velocity 

### ISSUE THREAD

**Issue by LizzWebb** [MITgcm/xmitgcm#278]
Hi all, 

I am trying to plot the U component of Sea Ice Velocity from the ECCO Portal for model 2160. To keep it simple, I am choosing time =0. However, the plot does not look reasonable. For example, it indicates sea ice velocity throughout, including at the equator, and very little velocity in the arctic (face 6). I am wondering if I am making an error in implementation? My lines of code are below, and I have attached the plot. 

Thank you in advance! 

```
model = llcreader.ECCOPortalLLC2160Model()
ds_SIvel= model.get_dataset(varnames=['SIuice','SIvice'], k_levels=[0])
SeaIce = ds_SIvel.SIuice
SeaIce.isel(time=0).plot.pcolormesh(cmap='coolwarm',vmin=-1, vmax=1, col='face', col_wrap=4)
```

![SIuice_world](https://user-images.githubusercontent.com/83596765/129655289-20cc435f-f5d4-492b-82de-99680a9effb1.png)

**Comment by mjlosch** [comment]
@LizzWebb 
The model (at the time of simulation, defaults have changed by now) has non-zero ice velocities also where there is no ice. They are just free drift velocities of ice with zero thickness. That's also why the Arctic velocities are so much smaller (because that's where the ice is, which does not move in free drift). But there's seems to be a problem with llcreader for this, because the drift field does not look physical.

I can reproduce that just for the Arctic with something like
```
from xmitgcm import llcreader
model = llcreader.ECCOPortalLLC2160Model()
ds=model.get_dataset(k_chunksize=90)
ds.SIuice.isel(time=100,face=6).plot.pcolormesh(ax=ax[0,0],vmin=-1,vmax=1)
```
and similarly for SIvice. Plotting SIheff (which lives on different grid points) works fine:
```
ds.SIheff.isel(time=100,face=6).plot.pcolormesh(ax=ax[0,0],vmin=0,vmax=4)
```
Interestingly the ocean velocities look fine, too (they use the same grid points as SIuice/vice).

Is this a bug in llcreader, or in the data set? @rabernat @menemenlis ?

Maybe related, I found this:
https://github.com/MITgcm/xmitgcm/blob/3b341ad8f43ea2b82e408c7c85011514deddfde6/xmitgcm/llcreader/llcutils.py#L11
Shouldn't that be 
```
    points = ['C', 'W', 'S']
```
to use/load all three types of masks?

**Comment by mjlosch** [comment]
The problem is related to #191 
Adding 'SIuice': 'c',  'SIvice': 'c' , to the 'mask_override' in xmitgcm/llcreader/known_models.py fixes the problem. I'll start a PR.

**Comment by rabernat** [comment]
@mjlosch thanks for digging into this. At first glance, it seems very similar to https://github.com/MITgcm/xmitgcm/issues/191. The winds, despite being on the velocity grid, have the c mask. That's why we use the `mask_override` parameter for reading winds:

https://github.com/MITgcm/xmitgcm/blob/3b341ad8f43ea2b82e408c7c85011514deddfde6/xmitgcm/llcreader/known_models.py#L59


And yes, looks like an embarrassing typo in `points = ['W', 'W', 'S']`. Unfortunately we don't have good test coverage for this.
