### ISSUE TITLE
Any obvious issues with velocities defined at the cell centre?

### ISSUE THREAD

**Issue by BWBlack** [MITgcm/xmitgcm#288]
Hello,

I'm currently working with llc 270 data (specifically [ecco darwin data](https://data.nas.nasa.gov/ecco/data.php?dir=/eccodata/llc_270/ecco_darwin_v5/output/monthly/uVel_C)). The velocities are defined at the cell centres and I am curious to find out whether this could have any implications for computing the transports? Have others encountered or used MITgcm velocity fields in this format before?

I apologise if this isn't the most appropriate place to raise this question, but it seemed sensible as xmitgcm is a key part of my work flow for this data.

Thanks,
Ben.

**Comment by timothyas** [comment]
Hey @BWBlack, I'm unfamiliar with the specifics of the ECCO Darwin output that you linked to, but since the MITgcm (and the wonderful LLC grid) uses an Arakawa C convention I bet that those velocities were interpolated onto cell center. This makes them easier to visualize, but as you're alluding to it means that interpolation error will enter into transport calculations. Additionally, on a finite volume grid the velocity is representative of a flux into (or out of) a grid cell, so when the velocity is "located" at cell center it's not clear what the (perhaps esoteric) interpretation of it is anymore.

All that to say, if you're really interested in computing transports I would recommend contacting someone involved with ECCO Darwin to see if can give you access to the native grid velocities, specifically UVELMASS and VVELMASS (in case the z* coordinate is used, these take the moving vertical coordinate into account). Then, you can use some routines from ecco_v4_py (see e.g. [here](https://ecco-v4-python-tutorial.readthedocs.io/ECCO_v4_Example_MHT.html) for an MHT example for the LLC grid). I'd be happy to help over at [ecco_v4_py](https://github.com/ECCO-GROUP/ECCOv4-py) if you have any issues with that.

I hope that helps!

**Comment by BWBlack** [comment]
Hi @timothyas, and thank you for clarifying this. That was my suspicion and the authors have just confirmed it, so I have now asked if they can make the native velocities available. Also ecco_v4_py looks ideal, so I may be in touch there soon. Cheers

**Comment by timothyas** [comment]
Great! I'm glad that was helpful. See you around :)
